/**
 * Columns that are generated by the database should be marked using
 * the `Generated` type. This way they are automatically made optional
 * in inserts and updates.
 *
 * You can specify a different type for each operation (select, insert and
 * update) using the `ColumnType<SelectType, InsertType, UpdateType>` wrapper.
 * Here we define a column `updated_at` that is selected as a `Date`, can
 * optionally be provided as a `string` in inserts and can never be updated.
 */

import type { CreateIndexBuilder, CreateTableBuilder, DropIndexBuilder } from 'kysely'
import { type Kysely, type RawBuilder, sql } from 'kysely'
import { serialize } from 'superjson'
import type { Database } from './db.schema'

// Postgres-specific function, returns the current timestamp in ISO8601 format.
// For zod compatibility, we need to use the ISO8601 format.
// Use this: z.string().datetime({ offset: true })
export const ISO_TIMESTAMP = sql`timezone('utc'::text, now())::timestamptz`

export const addColumnTimestamps = <T extends string, C extends string = never>(
  builder: CreateTableBuilder<T, C>
) => {
  return builder
    .addColumn('created_at', 'timestamptz', (col) => col.notNull().defaultTo(ISO_TIMESTAMP))
    .addColumn('updated_at', 'timestamptz', (col) => col.defaultTo(null))
}

export const addColumnSoftDelete = <T extends string, C extends string = never>(
  builder: CreateTableBuilder<T, C>
) => builder.addColumn('deleted_at', 'timestamptz', (col) => col.defaultTo(null))

/* @reference: https://www.kysely.dev/docs/recipes/relations */
export function json<T>(value: T): RawBuilder<T> {
  return sql`CAST(${serialize(value)} AS JSONB)`
}

export function dropTrigger(triggerName: string, tableName: string): RawBuilder<string> {
  return sql.raw(`DROP TRIGGER IF EXISTS ${triggerName} ON ${tableName};`)
}

export function dropTriggerUpdatedAt(table: string, schema = 'public'): RawBuilder<string> {
  return dropTrigger(`trg_${table}_updated_at`, `${schema}.${table}`)
}

export function createTriggerUpdatedAt(table: string, schema = 'public'): RawBuilder<string> {
  return sql.raw(`CREATE TRIGGER trg_${table}_updated_at
    BEFORE UPDATE ON ${schema}.${table} FOR EACH ROW
    EXECUTE FUNCTION ${schema}.fn_updated_at_value();
  `)
}

/**
 * Creates a basic index on a single column following project naming convention
 * @param db Database instance
 * @param table Table name
 * @param column Column name to index
 * @returns CreateIndexBuilder instance
 */
export const createColumnIndex = (
  db: Kysely<Database>,
  table: string,
  column: string
): CreateIndexBuilder => {
  return db.schema.createIndex(`idx_${table}_${column}`).on(table).column(column).ifNotExists()
}

/**
 * Creates a basic index on multiple columns following project naming convention
 * @param db Database instance
 * @param table Table name
 * @param columns Column names to index
 * @returns CreateIndexBuilder instance
 */
export const createColumnsIndex = (
  db: Kysely<Database>,
  table: string,
  columns: string[]
): CreateIndexBuilder => {
  return db.schema
    .createIndex(`idx_${table}_${columns.join('_')}`)
    .on(table)
    .columns(columns)
    .ifNotExists()
}

export const dropColumnIndex = (
  db: Kysely<Database>,
  table: string,
  column: string
): DropIndexBuilder => {
  const indexName = `idx_${table}_${column}`
  return db.schema.dropIndex(indexName).ifExists()
}

export const dropColumnsIndex = (
  db: Kysely<Database>,
  table: string,
  columns: string[]
): DropIndexBuilder => {
  const indexName = `idx_${table}_${columns.join('_')}`
  return db.schema.dropIndex(indexName).ifExists()
}
