/**
 * Columns that are generated by the database should be marked using
 * the `Generated` type. This way they are automatically made optional
 * in inserts and updates.
 *
 * You can specify a different type for each operation (select, insert and
 * update) using the `ColumnType<SelectType, InsertType, UpdateType>` wrapper.
 * Here we define a column `updated_at` that is selected as a `Date`, can
 * optionally be provided as a `string` in inserts and can never be updated.
 */

import { type CreateTableBuilder, type RawBuilder, sql } from 'kysely'
import { serialize } from 'superjson'

// Postgres-specific function, returns the current timestamp in ISO8601 format.
// For zod compatibility, we need to use the ISO8601 format.
// Use this: z.string().datetime({ offset: true })
export const ISO_TIMESTAMP = sql`timezone('utc'::text, now())::timestamptz`

// Use UUIDv7 as the default UUID generation strategy.
// NOTICE: This requires PostgreSQL version 18 or higher.
export const DEFAULT_UUID_v7 = sql`uuidv7()`

export const addColumnTimestamps = <T extends string, C extends string = never>(
  builder: CreateTableBuilder<T, C>
) => {
  return builder
    .addColumn('created_at', 'timestamptz', (col) => col.notNull().defaultTo(ISO_TIMESTAMP))
    .addColumn('updated_at', 'timestamptz', (col) => col.defaultTo(null))
}

export const addColumnSoftDelete = <T extends string, C extends string = never>(
  builder: CreateTableBuilder<T, C>
) => builder.addColumn('deleted_at', 'timestamptz', (col) => col.defaultTo(null))

/* @reference: https://www.kysely.dev/docs/recipes/relations */
export function json<T>(value: T): RawBuilder<T> {
  return sql`CAST(${serialize(value)} AS JSONB)`
}

export function dropTrigger(triggerName: string, tableName: string): RawBuilder<string> {
  return sql.raw(`DROP TRIGGER IF EXISTS ${triggerName} ON ${tableName};`)
}

export function dropTriggerUpdatedAt(table: string, schema = 'public'): RawBuilder<string> {
  return dropTrigger(`trg_${table}_updated_at`, `${schema}.${table}`)
}

export function createTriggerUpdatedAt(table: string, schema = 'public'): RawBuilder<string> {
  return sql.raw(`CREATE TRIGGER trg_${table}_updated_at
    BEFORE UPDATE ON ${schema}.${table} FOR EACH ROW
    EXECUTE FUNCTION ${schema}.fn_updated_at_value();
  `)
}
