import type { Sql } from 'postgres'
import { nowUtc } from '~/utils/datetime'

export function getSqlHeader(version: string): string {
  return `--
-- Generated by Squelify (${nowUtc()})
-- Database version: ${version}
--
-- Note: All CREATE statements are made idempotent with IF NOT EXISTS
-- System tables are excluded (_migration, _migration_lock)
--\n`
}

/**
 * Get formatted timestamp for filename in UTC
 * Format: YYYYMMDD-HHmmss
 */
export function getTimestamp(): string {
  const now = new Date()
  const year = now.getUTCFullYear()
  const month = String(now.getUTCMonth() + 1).padStart(2, '0')
  const day = String(now.getUTCDate()).padStart(2, '0')
  const hours = String(now.getUTCHours()).padStart(2, '0')
  const minutes = String(now.getUTCMinutes()).padStart(2, '0')
  const seconds = String(now.getUTCSeconds()).padStart(2, '0')

  return `${year}${month}${day}-${hours}${minutes}${seconds}`
}

export async function getDatabaseVersion(sql: Sql): Promise<string> {
  const versionResult = await sql<[{ version: string }]>`SELECT version();`
  return versionResult[0].version
}
